name: Lint and test
on:
  push

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:   
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17
      
      - name: Init docker swarm
        run: docker swarm init

      - name: Install Node.js dependencies
        run: yarn install

      - name: Lint and format
        run: yarn format

      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Commit Linting Fixes
        run: git diff-index --quiet HEAD || (git commit -a -m'[bot] auto fix' --allow-empty && git push -f)
     
