name: Lint
on:
  push

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:   
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17
      
      - name: init docker swarm
        run: docker swarm init

      # ESLint must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn

      - name: Lint and format
        run: yarn format

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Commit Linting Fixes
        run: |
          git add ./lib ./test
          git commit -m "Formatting & linting"
          git push origin main
      
     
